### ISSUE TITLE
Season Not Supported

### ISSUE THREAD

**Issue by kevmase** [naofireblade/homebridge-seasons#2]
Hi,

I have installed your plugin and the Home app is saying it is not supported?

Thanks
Kevin

**Comment by leoneleone** [comment]
@kevmase 
Have you tried using any other HomeKit apps? 
I suggest the Elgato Eve app

**Comment by naofireblade** [comment]
Hey @kevmase ,

as leoneleone said, you have to use another HomeKit app. The default app from apple does not support custom accessories types like the 4 seasons yet.
